"use client";

import { TestimonialCard } from "@/components/cards";
import { FadeInUp } from "@/components/ui";

interface Stat {
  number: string;
  text: string;
}

interface TestimonialData {
  image: string;
  testimonial: string;
  nameAndRole: string;
  company: string;
  companyLogo: string;
  stats: Stat[];
}

const testimonials: TestimonialData[] = [
  {
    image: "/tom.avif",
    testimonial:
      "I can enhance the agent or test new use cases directly, which allows us to respond quickly to business needs and continuously refine the experience.",
    nameAndRole: "TOM GUISGAND, SENIOR CUSTOMER JOURNEY DESIGNER",
    company: "Orange",
    companyLogo: "/customers/orange.avif",
    stats: [
      {
        number: "+50%",
        text: "Onboarding conversion rate improvement",
      },
      {
        number: "+10%",
        text: "customer satisfaction",
      },
      {
        number: "$4m+",
        text: "Yearly revenue GENERATED by one agent",
      },
    ],
  },
];

export default function Testimonials() {
  return (
    <section
      id="testimonials"
      className="py-20 lg:py-28 px-8 lg:px-20 bg-nexus-white"
    >
      <div className="max-w-[1440px] mx-auto ">
        {/* Header */}
        <FadeInUp className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6 lg:gap-10 mb-12 lg:mb-16">
          <h2 className="font-serif text-4xl lg:text-5xl font-normal text-nexus-black leading-tight">
            Proven solutions{" "}
            <br/>Across industries
          </h2>
          {/* Navigation buttons would go here if needed */}
        </FadeInUp>

        {/* Testimonial Cards - Horizontal Scroll on Desktop */}
        <FadeInUp delay={0.15}>
          <div className="flex gap-4 lg:min-w-0">
            {testimonials.map((testimonial, index) => (
              <TestimonialCard
                key={index}
                {...testimonial}
                className="lg:min-w-0"
              />
            ))}
          </div>
        </FadeInUp>
      </div>
    </section>
  );
}
