"use client";

import TestimonialCard from "./TestimonialCard";

interface Stat {
  number: string;
  text: string;
}

interface TestimonialData {
  image: string;
  testimonial: string;
  nameAndRole: string;
  company: string;
  companyLogo: string;
  stats: Stat[];
}

const testimonials: TestimonialData[] = [
  {
    image: "/tom.avif",
    testimonial:
      "I can enhance the agent or test new use cases directly, which allows us to respond quickly to business needs and continuously refine the experience.",
    nameAndRole: "TOM GUISGAND, SENIOR CUSTOMER JOURNEY DESIGNER",
    company: "Orange",
    companyLogo: "/customers/orange.avif",
    stats: [
      {
        number: "+50%",
        text: "Improvement in onboarding CONVERSION RATE",
      },
      {
        number: "+10%",
        text: "faster proposal generation",
      },
      {
        number: ">300k$",
        text: "MONTHLY revenue GENERATED by one agent",
      },
    ],
  },
];

export default function Testimonials() {
  return (
    <section
      id="testimonials"
      className="py-20 md:py-28 px-8 md:px-20 bg-nexus-white"
    >
      <div className="max-w-[1440px] mx-auto">
        {/* Header */}
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6 md:gap-10 mb-12 md:mb-16">
          <h2 className="font-serif text-4xl md:text-5xl font-normal text-nexus-black leading-tight">
            Proven Solutions{" "}
            <span className="tracking-tight">Across Industries</span>
          </h2>
          {/* Navigation buttons would go here if needed */}
        </div>

        {/* Testimonial Cards - Horizontal Scroll on Desktop */}
        <div className="overflow-x-auto md:overflow-x-visible">
          <div className="flex gap-4 md:gap-4 min-w-max md:min-w-0">
            {testimonials.map((testimonial, index) => (
              <TestimonialCard
                key={index}
                {...testimonial}
                className="min-w-[358px] md:min-w-0"
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
